-- ============================================================
-- 0001_init — safe MVP schema for CuasarX Longevity
-- Idempotent: safe to run more than once.
--
-- Fixes over the original supabase/schema.sql, which exposed all
-- health data publicly:
--   * No policy grants anything to anon for user-owned tables
--   * Profiles / regimens / biomarker_logs / orders are locked to
--     auth.uid() = user_id with explicit per-command policies
--   * Foreign keys are indexed; updated_at maintained by trigger
--   * Status values constrained with CHECK
-- ============================================================

create extension if not exists pgcrypto;

-- ---------- profiles ----------
create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  name text not null default 'New Member',
  email text,
  lifestyle_persona text,
  baseline_diagnostics jsonb default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists profiles_user_id_idx on public.profiles(user_id);

-- ---------- products (catalog) ----------
create table if not exists public.products (
  id text primary key,
  name text not null,
  category text not null,
  price numeric(10,2) not null check (price >= 0),
  description text,
  dosage text,
  timing text,
  evidence_grade char(1) check (evidence_grade in ('A','B','C')),
  tailored_reason text,
  created_at timestamptz not null default now()
);

-- ---------- orders ----------
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  items jsonb not null,
  subtotal numeric(10,2) not null,
  discount numeric(10,2) not null default 0,
  tax numeric(10,2) not null default 0,
  shipping numeric(10,2) not null default 0,
  total numeric(10,2) not null,
  payment_status text not null default 'test_simulated'
    check (payment_status in ('test_simulated','paid','refunded')),
  fulfillment_status text not null default 'processing'
    check (fulfillment_status in ('processing','packed','shipped','delivered','cancelled')),
  shipping_address jsonb,
  created_at timestamptz not null default now()
);
create index if not exists orders_user_id_idx on public.orders(user_id);

-- Human-friendly order numbers generated by the database.
create sequence if not exists orders_number_seq start 100000;
alter table public.orders alter column order_number
  set default 'CX-' || nextval('orders_number_seq')::text;

-- ---------- biomarker readings (one row per reading, not a JSONB blob) ----------
create table if not exists public.biomarker_readings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  biomarker_name text not null,
  value numeric(10,2) not null,
  unit text not null,
  recorded_at timestamptz not null default now()
);
create index if not exists biomarker_readings_user_idx on public.biomarker_readings(user_id, recorded_at desc);

-- ---------- daily regimens ----------
create table if not exists public.user_regimens (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id text references public.products(id) on delete set null,
  custom_name text,
  dosage text not null default '',
  timing text not null default '',
  frequency_days int not null default 30 check (frequency_days between 1 and 365),
  is_subscription boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists user_regimens_user_idx on public.user_regimens(user_id);

-- ---------- updated_at trigger ----------
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at
  before update on public.profiles
  for each row execute function public.touch_updated_at();

-- ============================================================
-- ROW LEVEL SECURITY — the critical fix.
-- ============================================================
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.biomarker_readings enable row level security;
alter table public.user_regimens enable row level security;

-- Remove ALL pre-existing policies on these tables (including the unsafe
-- ones from the old schema.sql if it was ever applied). Conditional so the
-- migration also works on projects where the old tables never existed.
do $$
declare
  t text;
  pol record;
begin
  foreach t in array array['profiles','products','orders','biomarker_readings','user_regimens','biomarker_logs'] loop
    if exists (select 1 from information_schema.tables where table_schema = 'public' and table_name = t) then
      for pol in select policyname from pg_policies where schemaname = 'public' and tablename = t loop
        execute format('drop policy if exists %I on public.%I', pol.policyname, t);
      end loop;
    end if;
  end loop;
end $$;

-- Products: world-readable catalog (anon + authenticated).
drop policy if exists "products are readable by everyone" on public.products;
create policy "products are readable by everyone"
  on public.products for select using (true);

-- User-owned tables: strictly auth.uid() = user_id, per command.
-- (No anon access, no USING (true), service_role bypasses RLS by design.)

drop policy if exists "select own profile" on public.profiles;
create policy "select own profile" on public.profiles
  for select using (auth.uid() = user_id);
drop policy if exists "insert own profile" on public.profiles;
create policy "insert own profile" on public.profiles
  for insert with check (auth.uid() = user_id);
drop policy if exists "update own profile" on public.profiles;
create policy "update own profile" on public.profiles
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "delete own profile" on public.profiles;
create policy "delete own profile" on public.profiles
  for delete using (auth.uid() = user_id);

drop policy if exists "select own orders" on public.orders;
create policy "select own orders" on public.orders
  for select using (auth.uid() = user_id);
drop policy if exists "insert own orders" on public.orders;
create policy "insert own orders" on public.orders
  for insert with check (auth.uid() = user_id);

drop policy if exists "select own readings" on public.biomarker_readings;
create policy "select own readings" on public.biomarker_readings
  for select using (auth.uid() = user_id);
drop policy if exists "insert own readings" on public.biomarker_readings;
create policy "insert own readings" on public.biomarker_readings
  for insert with check (auth.uid() = user_id);

drop policy if exists "select own regimens" on public.user_regimens;
create policy "select own regimens" on public.user_regimens
  for select using (auth.uid() = user_id);
drop policy if exists "insert own regimens" on public.user_regimens;
create policy "insert own regimens" on public.user_regimens
  for insert with check (auth.uid() = user_id);
drop policy if exists "update own regimens" on public.user_regimens;
create policy "update own regimens" on public.user_regimens
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "delete own regimens" on public.user_regimens;
create policy "delete own regimens" on public.user_regimens
  for delete using (auth.uid() = user_id);
